version: '1.0'
stocks:
- code: '688409'
  name: 富创精密
- code: '300843'
  name: 胜蓝股份
- code: '688008'
  name: 澜起科技
- code: '688041'
  name: 海光信息
- code: '688027'
  name: 国盾量子
- code: '301666'
  name: 大普微
- code: '688797'
  name: 臻宝
- code: '920045'
  name: 蘅东光
- code: '688820'
  name: 盛合晶微
- code: '688028'
  name: 沃尔德
- code: '300757'
  name: 罗博特科
- code: '688521'
  name: 芯原股份
- code: '002975'
  name: 博杰股份
- code: '300083'
  name: 创世纪
- code: '688392'
  name: 骄成超声
- code: '300480'
  name: 光力科技
- code: '301392'
  name: 汇成真空
- code: '300308'
  name: 中际旭创
- code: '688048'
  name: 长光华芯
- code: '603986'
  name: 兆易创新
- code: '688361'
  name: 中科飞测
- code: '688630'
  name: 芯碁微装
- code: '688328'
  name: 深科达
- code: '603061'
  name: 金海通
- code: '688627'
  name: 精智达           

